Update 3-install-free5gc.md
In free5gc-compose, building with 1.17.8 fails with errors like [#12 15.50 /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/binding/form.go:22:48: undefined: any] which is fixed in 1.18

Full error logs: https://github.com/free5gc/free5gc-compose/actions/runs/6147575308/job/17345854254
Fixed by: https://github.com/free5gc/free5gc-compose/commit/7f7cec7987f2268a6cd2bc7c755bad8c67da81a7